### PR TITLE
Feature/travis

### PR DESCRIPTION
**Pull request by adamkudrna**

### CODE REVIEW

**Comment by adamkudrna** [comment]
I'm sorry, wrong repository (♥️ GitHub UI…).

**Comment by OndraM** [comment]
@adamkudrna Hi, and aren't you interested to send the changes to the upstream? Would be great to join forces :-).

**Comment by adamkudrna** [comment]
@OndraM in case you are interested in switching to flexbox, why not :-). However, we should start from scratch then as our fork now also contains older changes that are no longer valid and one would not want to see them in the project's history.

**Comment by OndraM** [comment]
@adamkudrna Sorry, no plans for implementing flexbox. For the future we are [rather](https://jakearchibald.com/2014/dont-use-flexbox-for-page-layout/) watching over CSS Grid.

**Comment by adamkudrna** [comment]
I understand, [so are we](http://caniuse.com/#feat=css-grid).

I also hear one of your teams is using our fork of Emerald. We were really surprised when we found out because we forked Emerald only for our purposes and did not mean to distribute it to anyone to use it in production :-). We are not going to use that version (before our v2.0) any longer but we are open to clean up the Git history and contribute properly to your repo if it is interesting to you.

**Comment by OndraM** [comment]
Well, they were actually surprised as well, because it was some unknown and unintentional relic of past Synergic development ;-). AFAIK they no longer use it nowadays.

**Comment by adamkudrna** [comment]
OK, good for them :-).

**Pull request closed without merging**
